<?xml version="1.0"?>
<robot xmlns:xacro="http://ww.ros.org/wiki/xacro" >
    <!-- FILE INCLUSION ZONE -->>
    <xacro:include filename="materials.xacro"/>
    <xacro:include filename="inertial_macros.xacro"/> <!--from the articulated robotics URDF tutorial-->>
    
    <!-- Starting point of the CRAFT -->
    <link name="base_link"> 

    </link>

    <!-- HULL LINK ===========================================-->
    <joint name="hull_joint" type="fixed">
        <parent link="base_link"/>
        <child link="hull"/>
        <origin xyz="0.1 0.0 0.0"/>
    </joint>

    <link name="hull">
        <visual>
            <!--make the z how far it should flaot above the simuilated water-->
            <origin xyz="0.1 0.0 0.5" rpy = "0.0 0.0 0.0"/>
            <geometry>
                <box size="${hull_length} ${hull_width} ${hull_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <!-- for now, make the colission geomentry the same as the basic box shape -->
            <origin xyz="0.1 0.0 0.5" rpy = "0.0 0.0 0.0"/>
            <geometry>
                <box size="${hull_length} ${hull_width} ${hull_height}"/>
            </geometry>
        </collision>
		<!-- TODO define the mass here - using placeholder 1.5 kg -->
        <xacro:inertial_box mass="${CRAFT_mass}" x="${hull_length}" y="${hull_width}" z="${hull_height}">
            <origin xyz="0.1 0.0 0.0" rpy = "0.0 0.0 0.0"/>
        </xacro:inertial_box>
	</link>

    <gazebo reference="hull">
    	<material>Gazebo/Orange</material> <!--Do we need to add a material section to the launch file now?-->
        <mu1 = "0.0001"/>
        <mu2 = "0.0001"/> <!--these are both needed for the lack of friction-->
    </gazebo>

    <!-- MOTOR LINK ===========================================-->>
        <!--the motor and servo link will probably need the joint state publisher gui to be seen-->
    <joint name="motor_joint" type="continuous">
        <parent link="base_link"/>
        <child link="motor"/>
        <origin xyz="0.2 0.0 0.0" rpy="-${pi/2} 0.0 0.0"/>
        <!-- "CW forward CCW backward" -Eric -->
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <link name="motor">
        <visual>
            <geometry>
                <cylinder radius="${motor_radius}" length="${motor_length}"/>
            </geometry>
            <material name="green"/>
        </visual>
    </link>

    <gazebo reference="motor">
    	<material>Gazebo/green</material> 
    </gazebo>

    <!-- SERVO LINK ===========================================-->>
    <joint name="servo_joint" type="continuous">    
        <parent link="base_link"/>
        <child link="servo"/>
        <origin xyz="0.2 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <!-- "Turning right is clockwise" -->
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <link name="servo">
        <visual>
            <geometry>
                <cylinder radius="${servo_radius}" length="${servo_length}"/>
            </geometry>
            <material name="white"/>
        </visual>
    </link>

    <gazebo reference="servo">
    	<material>Gazebo/White</material> 
    </gazebo>

    <!-- TRNSMISSION ===========================================--> <!--fix, may not be needed...-->>
    <transmission name="rudder_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="servo_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="rudder_motor">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


    <!-- ANTENNA SECTION ============================================================================-->
    <!-- the antennas are position as following: 
                    Front
                      ^
            Left |  4   1  |  Right
                 |  3   2  |
                    _____
                     Back
            Y
            |_X
          Z/
    -->
    <joint name="antenna_center_joint" type="fixed">
        <parent link="base_link"/>
        <child link="antenna_center"/>
        <origin xyz="${hull_length/2 - antenna_center_offset} ${hull_length} 0.0"/> <!--I think base_link is centered on the otooom, so the nase antenna center should be UP and more forward-->
    </joint>
    <joint name="antenna_1_joint" type="fixed">
        <parent link="antenna_center"/>
        <child link="antenna_1"/>
        <origin xyz="${antenna_spacing} 0.0 ${antenna_spacing}"/> <!--I think base_link is centered on the otooom, so the nase antenna center should be UP and more forward-->
    </joint>
    <joint name="antenna_2_joint" type="fixed">
        <parent link="antenna_center"/>
        <child link="antenna_2"/>
        <origin xyz="${antenna_spacing} 0.0 -${antenna_spacing}"/> <!--I think base_link is centered on the otooom, so the nase antenna center should be UP and more forward-->
    </joint>
    <joint name="antenna_3_joint" type="fixed">
        <parent link="antenna_center"/>
        <child link="antenna_3"/>
        <origin xyz="-${antenna_spacing} 0.0 -${antenna_spacing}"/> <!--I think base_link is centered on the otooom, so the nase antenna center should be UP and more forward-->
    </joint>
    <joint name="antenna_4_joint" type="fixed">
        <parent link="antenna_center"/>
        <child link="antenna_4"/>
        <origin xyz="-${antenna_spacing} 0.0 ${antenna_spacing}"/> <!--I think base_link is centered on the otooom, so the nase antenna center should be UP and more forward-->
    </joint>

        <!--Antenna Antennai Extrusions-->
    <link name="antenna_1">
        <visual>
            <geometry>
                <cylinder radius="${antenna_radius}" length="${antenna_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <link name="antenna_2">
        <visual>
            <geometry>
                <cylinder radius="${antenna_radius}" length="${antenna_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <link name="antenna_3">
        <visual>
            <geometry>
                <cylinder radius="${antenna_radius}" length="${antenna_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>
    <link name="antenna_4">
        <visual>
            <geometry>
                <cylinder radius="${antenna_radius}" length="${antenna_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
    </link>

        <!--Gazebo Colors-->
    <gazebo reference="antenna_1">
    	<material>Gazebo/Blue</material> 
    </gazebo>
    <gazebo reference="antenna_2">
    	<material>Gazebo/Blue</material> 
    </gazebo>
    <gazebo reference="antenna_3">
    	<material>Gazebo/Blue</material> 
    </gazebo>
    <gazebo reference="antenna_4">
    	<material>Gazebo/Blue</material> 
    </gazebo>

</robot>
